// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hub/hub.proto

package hub

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 发往上游
type ReqInsertOrder struct {
	TaId                 string   `protobuf:"bytes,1,opt,name=ta_id,json=taId,proto3" json:"taId"`
	BuId                 string   `protobuf:"bytes,2,opt,name=bu_id,json=buId,proto3" json:"buId"`
	Exchange             string   `protobuf:"bytes,3,opt,name=exchange,proto3" json:"exchange"`
	Symbol               string   `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol"`
	FrontId              int32    `protobuf:"varint,5,opt,name=front_id,json=frontId,proto3" json:"frontId"`
	SessionId            int32    `protobuf:"varint,6,opt,name=session_id,json=sessionId,proto3" json:"sessionId"`
	OrderRef             string   `protobuf:"bytes,7,opt,name=order_ref,json=orderRef,proto3" json:"orderRef"`
	Product              string   `protobuf:"bytes,8,opt,name=product,proto3" json:"product"`
	Direction            int32    `protobuf:"varint,9,opt,name=direction,proto3" json:"direction"`
	Offset               int32    `protobuf:"varint,10,opt,name=offset,proto3" json:"offset"`
	Price                float64  `protobuf:"fixed64,11,opt,name=price,proto3" json:"price"`
	Volume               int32    `protobuf:"varint,12,opt,name=volume,proto3" json:"volume"`
	PriceType            int32    `protobuf:"varint,13,opt,name=price_type,json=priceType,proto3" json:"priceType"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqInsertOrder) Reset()         { *m = ReqInsertOrder{} }
func (m *ReqInsertOrder) String() string { return proto.CompactTextString(m) }
func (*ReqInsertOrder) ProtoMessage()    {}
func (*ReqInsertOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_87629b1556de20e1, []int{0}
}

func (m *ReqInsertOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqInsertOrder.Unmarshal(m, b)
}
func (m *ReqInsertOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqInsertOrder.Marshal(b, m, deterministic)
}
func (m *ReqInsertOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqInsertOrder.Merge(m, src)
}
func (m *ReqInsertOrder) XXX_Size() int {
	return xxx_messageInfo_ReqInsertOrder.Size(m)
}
func (m *ReqInsertOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqInsertOrder.DiscardUnknown(m)
}

var xxx_messageInfo_ReqInsertOrder proto.InternalMessageInfo

func (m *ReqInsertOrder) GetTaId() string {
	if m != nil {
		return m.TaId
	}
	return ""
}

func (m *ReqInsertOrder) GetBuId() string {
	if m != nil {
		return m.BuId
	}
	return ""
}

func (m *ReqInsertOrder) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *ReqInsertOrder) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *ReqInsertOrder) GetFrontId() int32 {
	if m != nil {
		return m.FrontId
	}
	return 0
}

func (m *ReqInsertOrder) GetSessionId() int32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *ReqInsertOrder) GetOrderRef() string {
	if m != nil {
		return m.OrderRef
	}
	return ""
}

func (m *ReqInsertOrder) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func (m *ReqInsertOrder) GetDirection() int32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

func (m *ReqInsertOrder) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ReqInsertOrder) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ReqInsertOrder) GetVolume() int32 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *ReqInsertOrder) GetPriceType() int32 {
	if m != nil {
		return m.PriceType
	}
	return 0
}

// 撤单
type ReqCancelOrder struct {
	TaId                 string   `protobuf:"bytes,1,opt,name=ta_id,json=taId,proto3" json:"taId"`
	BuId                 string   `protobuf:"bytes,2,opt,name=bu_id,json=buId,proto3" json:"buId"`
	Exchange             string   `protobuf:"bytes,3,opt,name=exchange,proto3" json:"exchange"`
	Symbol               string   `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol"`
	FrontId              int32    `protobuf:"varint,5,opt,name=front_id,json=frontId,proto3" json:"frontId"`
	SessionId            int32    `protobuf:"varint,6,opt,name=session_id,json=sessionId,proto3" json:"sessionId"`
	OrderRef             string   `protobuf:"bytes,7,opt,name=order_ref,json=orderRef,proto3" json:"orderRef"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCancelOrder) Reset()         { *m = ReqCancelOrder{} }
func (m *ReqCancelOrder) String() string { return proto.CompactTextString(m) }
func (*ReqCancelOrder) ProtoMessage()    {}
func (*ReqCancelOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_87629b1556de20e1, []int{1}
}

func (m *ReqCancelOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCancelOrder.Unmarshal(m, b)
}
func (m *ReqCancelOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCancelOrder.Marshal(b, m, deterministic)
}
func (m *ReqCancelOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCancelOrder.Merge(m, src)
}
func (m *ReqCancelOrder) XXX_Size() int {
	return xxx_messageInfo_ReqCancelOrder.Size(m)
}
func (m *ReqCancelOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCancelOrder.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCancelOrder proto.InternalMessageInfo

func (m *ReqCancelOrder) GetTaId() string {
	if m != nil {
		return m.TaId
	}
	return ""
}

func (m *ReqCancelOrder) GetBuId() string {
	if m != nil {
		return m.BuId
	}
	return ""
}

func (m *ReqCancelOrder) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *ReqCancelOrder) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *ReqCancelOrder) GetFrontId() int32 {
	if m != nil {
		return m.FrontId
	}
	return 0
}

func (m *ReqCancelOrder) GetSessionId() int32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *ReqCancelOrder) GetOrderRef() string {
	if m != nil {
		return m.OrderRef
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqInsertOrder)(nil), "goshare.hub.ReqInsertOrder")
	proto.RegisterType((*ReqCancelOrder)(nil), "goshare.hub.ReqCancelOrder")
}

func init() { proto.RegisterFile("hub/hub.proto", fileDescriptor_87629b1556de20e1) }

var fileDescriptor_87629b1556de20e1 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x92, 0xbd, 0x4e, 0xf3, 0x30,
	0x14, 0x86, 0x95, 0x7e, 0x4d, 0xdb, 0xb8, 0x5f, 0x19, 0x0c, 0x42, 0xe6, 0x4f, 0xaa, 0x3a, 0x45,
	0x0c, 0xcd, 0xc0, 0x1d, 0xc0, 0x94, 0x09, 0x29, 0x62, 0x62, 0xa9, 0xe2, 0xf8, 0x24, 0xb1, 0x48,
	0x6c, 0xe3, 0x1f, 0x44, 0x2f, 0x90, 0x1b, 0xe1, 0x4a, 0x90, 0xed, 0xd0, 0x7b, 0x60, 0x7c, 0x9e,
	0xf7, 0xc8, 0x3e, 0x3a, 0x7a, 0xd1, 0xa6, 0x77, 0xb4, 0xe8, 0x1d, 0xdd, 0x2b, 0x2d, 0xad, 0xc4,
	0xeb, 0x4e, 0x9a, 0xbe, 0xd6, 0xb0, 0xef, 0x1d, 0xdd, 0x7d, 0xcf, 0xd0, 0x59, 0x05, 0xef, 0xa5,
	0x30, 0xa0, 0xed, 0xb3, 0x66, 0xa0, 0xf1, 0x39, 0x4a, 0x6d, 0x7d, 0xe0, 0x8c, 0x24, 0xdb, 0x24,
	0xcf, 0xaa, 0xb9, 0xad, 0x4b, 0xe6, 0x25, 0x75, 0x5e, 0xce, 0xa2, 0xa4, 0xae, 0x64, 0xf8, 0x1a,
	0xad, 0xe0, 0xb3, 0xe9, 0x6b, 0xd1, 0x01, 0xf9, 0x17, 0xfc, 0x89, 0xf1, 0x25, 0x5a, 0x98, 0xe3,
	0x48, 0xe5, 0x40, 0xe6, 0x21, 0x99, 0x08, 0x5f, 0xa1, 0x55, 0xab, 0xa5, 0xb0, 0xfe, 0xad, 0x74,
	0x9b, 0xe4, 0x69, 0xb5, 0x0c, 0x5c, 0x32, 0x7c, 0x87, 0x90, 0x01, 0x63, 0xb8, 0x14, 0x3e, 0x5c,
	0x84, 0x30, 0x9b, 0x4c, 0xc9, 0xf0, 0x0d, 0xca, 0xa4, 0x5f, 0xf0, 0xa0, 0xa1, 0x25, 0xcb, 0xf8,
	0x5d, 0x10, 0x15, 0xb4, 0x98, 0xa0, 0xa5, 0xd2, 0x92, 0xb9, 0xc6, 0x92, 0x55, 0x88, 0x7e, 0x11,
	0xdf, 0xa2, 0x8c, 0x71, 0x0d, 0x8d, 0xe5, 0x52, 0x90, 0x2c, 0x3e, 0x7a, 0x12, 0x7e, 0x4d, 0xd9,
	0xb6, 0x06, 0x2c, 0x41, 0x21, 0x9a, 0x08, 0x5f, 0xa0, 0x54, 0x69, 0xde, 0x00, 0x59, 0x6f, 0x93,
	0x3c, 0xa9, 0x22, 0xf8, 0xe9, 0x0f, 0x39, 0xb8, 0x11, 0xc8, 0xff, 0x38, 0x1d, 0xc9, 0x6f, 0x1e,
	0x06, 0x0e, 0xf6, 0xa8, 0x80, 0x6c, 0xe2, 0x27, 0xc1, 0xbc, 0x1c, 0x15, 0xec, 0xbe, 0x92, 0x70,
	0xe4, 0xa7, 0x5a, 0x34, 0x30, 0xfc, 0xdd, 0x23, 0x3f, 0xde, 0xbf, 0xe6, 0x1d, 0xb7, 0xbe, 0x49,
	0x8d, 0x1c, 0x8b, 0x91, 0x0b, 0xd0, 0xf5, 0xa0, 0xc1, 0x14, 0x53, 0xa3, 0x0a, 0xf5, 0xd6, 0x15,
	0x2a, 0x74, 0x8d, 0x2e, 0x42, 0xd9, 0x1e, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x5c, 0x08, 0x2a,
	0x7d, 0x7d, 0x02, 0x00, 0x00,
}
